version: '3.1'
services:
    postgres:
        image: 'postgres:15-alpine'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=admin
        ports:
            - '45004:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            - './dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '45000:80'

    php-fpm:
        build: dev/php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            - './dev/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
